# **Preprocessing the CERT Dataset**:

### Imports:

In [1]:
from scripts.Preprocessing import *

### Defining Constants and Defining CERT Path:

In [2]:
CERT_PATH = r"C:\Users\loera\Documents\Datasets\CERT_r6.2"
WORK_HOURS = (9, 17)
LONG_URL_THRESHOLD = 90
DEFAULT_OUTPUT_DIR = "ueba_dataset_4"

### Building Layer A: (User, PC, Day) Level Dataset

In [3]:
layer_a_dataset = build_layer_a(cert_path=CERT_PATH, work_hours=WORK_HOURS)

email.csv will be normalized when loaded per-chunk
http.csv will be normalized when loaded per-chunk

In [4]:
layer_a_dataset.head()

,user,pc,day,logon_count,logoff_count,off_hours_logon,file_open_count,file_write_count,file_copy_count,file_delete_count,...,off_hours_http_requests,http_long_url_count,unique_domains_visited,pc_prior_use_count,pc_seen_before,pc_prior_use_ratio,pc_is_primary,distinct_pcs_used_prior,n_pcs_used_today,new_pc_after_stable_history
0,aab0162,pc-6599,2010-01-04,1,1,2,0,0,0,0,...,32,34,16,0,0,0.0,1,0,1,0
1,aab0162,pc-6599,2010-01-05,1,1,2,0,0,0,0,...,22,27,14,1,1,1.0,1,1,1,0
2,aab0162,pc-6599,2010-01-06,1,1,2,0,0,0,0,...,15,54,19,2,1,1.0,1,1,1,0
3,aab0162,pc-6599,2010-01-07,1,1,2,0,0,0,0,...,25,44,26,3,1,1.0,1,1,1,0
4,aab0162,pc-6599,2010-01-08,1,1,2,0,0,0,0,...,30,42,10,4,1,1.0,1,1,1,0

In [ ]:
layer_a_path = save_dataset(
    dataset=layer_a_dataset,
    filename="ueba_dataset_4a.csv",
    output_dir=DEFAULT_OUTPUT_DIR
)

Dataset successfully saved to: c:\Users\loera\Documents\Insider-Threat-Detection\processed_datasets\ueba_dataset_4\ueba_dataset_4a.csv

### Building Layer B: (User, Day) Model Training Dataset

In [6]:
layer_b_dataset = build_layer_b(
    layer_a_df=layer_a_dataset,
    rolling_window=5
)

In [7]:
layer_b_dataset.head()

,user,day,logon_count,logoff_count,off_hours_logon,file_open_count,file_write_count,file_copy_count,file_delete_count,unique_files_accessed,...,non_primary_pc_http_requests_flag_rolling_delta,non_primary_pc_usb_flag_rolling_delta,non_primary_pc_file_copy_flag_rolling_delta,off_hours_activity_flag,usb_file_activity_flag,external_comm_activity_flag,jobsite_usb_activity_flag,suspicious_upload_flag,cloud_upload_flag,non_primary_pc_risk_flag
0,aab0162,2010-01-04,1,1,2,0,0,0,0,0,...,0.0,0.0,0.0,1,0,1,0,0,0,0
1,aab0162,2010-01-05,1,1,2,0,0,0,0,0,...,0.0,0.0,0.0,1,0,1,0,0,0,0
2,aab0162,2010-01-06,1,1,2,0,0,0,0,0,...,0.0,0.0,0.0,1,0,0,0,0,0,0
3,aab0162,2010-01-07,1,1,2,0,0,0,0,0,...,0.0,0.0,0.0,1,0,1,0,0,0,0
4,aab0162,2010-01-08,1,1,2,0,0,0,0,0,...,0.0,0.0,0.0,1,0,1,0,0,0,0

In [8]:
layer_b_path = save_dataset(
    dataset=layer_b_dataset,
    filename="ueba_dataset_4b.csv",
    output_dir=DEFAULT_OUTPUT_DIR)

Dataset successfully saved to: c:\Users\loera\Documents\Insider-Threat-Detection\processed_datasets\ueba_dataset_4\ueba_dataset_4b.csv

### Creating the Chronological Train/Test Split

In [ ]:
# Splitting dataset B
train_df, test_df = chronological_split(df=layer_b_dataset, split_ratio=0.9)

In [ ]:
# Saving training and testing sets
train_path = save_dataset(train_df, "ueba_dataset_4_train.csv", DEFAULT_OUTPUT_DIR)
test_path = save_dataset(test_df, "ueba_dataset_4_test_stream.csv", DEFAULT_OUTPUT_DIR)

Dataset successfully saved to: c:\Users\loera\Documents\Insider-Threat-Detection\processed_datasets\ueba_dataset_4\ueba_dataset_4_train.csv
Dataset successfully saved to: c:\Users\loera\Documents\Insider-Threat-Detection\processed_datasets\ueba_dataset_4\ueba_dataset_4_test_stream.csv

###  Utilizing Drill-Down Dataset Lookup

In [12]:
# Example usage
user = "abh0349"
day = "2010-01-27"

In [13]:
drill_down_table = get_drilldown(layer_a_dataset, user, day)

In [14]:
drill_down_table

,user,pc,day,logon_count,logoff_count,off_hours_logon,file_open_count,file_write_count,file_copy_count,file_delete_count,...,off_hours_http_requests,http_long_url_count,unique_domains_visited,pc_prior_use_count,pc_seen_before,pc_prior_use_ratio,pc_is_primary,distinct_pcs_used_prior,n_pcs_used_today,new_pc_after_stable_history
11356,abh0349,pc-1019,2010-01-27,2,1,1,0,0,0,0,...,2,7,7,17,1,0.809524,1,5,2,0
11357,abh0349,pc-1534,2010-01-27,1,1,0,0,0,0,0,...,0,0,0,0,0,0.000000,0,5,2,1